name: Remote workflow
on:
  push:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: farhan-TheITguy/hello-action/.github/workflows/get-prefix.yml@main
    secrets: inherit
    with:
      deployment-type: 'supersite'