name: Test Workflow
on:
  push:
  workflow_dispatch:
jobs:
    prefix-db:
      name: get, release or seed
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: prefix-db
          uses: farhan-TheITguy/hello-action@main
          with:
            deployment-type: supersite
            operation: release