name: Test Workflow
on:
  push:
  workflow_dispatch:
jobs:
  greet:
    name: Greet someone
    runs-on: ubuntu-latest
    steps:
      - uses: farhan-TheITguy/hello-action/.github/actions/hello@main
