name: Test Workflow
on:
  push:
  workflow_dispatch:
jobs:
  hello:
    uses: farhan-TheITguy/hello-action/.github/workflows/hello.yml@main
    with:
      who-to-greet: 'Mona the Octocat'
  bye:
    uses: ffarhan-TheITguy/hello-action/.github/workflows/bye.yml@main
    with:
      who-to-greet: 'Mona the Octocat'
