name: Test Workflow
on:
  push:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: hello
        uses: farhan-TheITguy/hello-action/.github/actions/hello.yml@main
        with:
          who-to-greet: 'Mona the Octocat'
      # - run: echo random-number "$RANDOM_NUMBER"
      #   shell: bash
      #   env:
      #     RANDOM_NUMBER: ${{ steps.hello.outputs.random-number }}
      - id: bye
        uses: farhan-TheITguy/hello-action/.github/actions/bye.yml@main
        with:
          who-to-greet: 'Mona the Octocat'