name: Remote workflow
on:
  push:
  workflow_dispatch:
    inputs:
      deployment-type:
        type: string
        description: site or supersite
        default: site

jobs:

  get-prefix:
    uses: farhan-TheITguy/hello-action/.github/workflows/get-prefix.yml@main
    secrets: inherit
    with:
      deployment-type: 'supersite'

  post:
    name: pre
    runs-on: ubuntu-latest
    needs: [get-prefix]
    env:
      prefix: ${{ needs.get-prefix.outputs.environment-prefix }}
    steps:
      - shell: bash
        run: |
          echo "Here I am printing the secrets and prefix from caller"
          echo "Password: ${{ secrets.NEW_PASS }}"
          echo "Prefix: ${{ env.prefix }}"